### ISSUE TITLE
Is there an a-ngclick snippet?

### ISSUE THREAD

**Issue by nbarkhina** [johnpapa/vscode-angular-snippets#101]
This may be a feature request but was just wondering if there's a way to have the click snippet. Seems like all the other ones are covered. Otherwise great tool.

Thanks!

> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution).macOS(Yosemite ? El Capitan? Sierra ?)

### Versions
  >

### Repro steps
  >

### The log given by the failure.
>

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
perhaps. what would you want it to do?

**Comment by nbarkhina** [comment]
Would be great if typing a-ngclick would just fill out this snippet

(click)=""

and then have the cursor ready to type inside of the quotes. just seems like something that is typed so often and would be a great time saver.

Thanks

**Comment by Sampath-Lokuge** [comment]
Yes, I also like this feature.

**Comment by doggy8088** [comment]
@nbarkhina @Sampath-Lokuge I think the **Angular Language Service** already have the intellisense on all events. The `a-ngclick` don't really save you time.

For a developer experience, you can type this way to achieve your goal:

```sh
(c<TAB>"
```

**Comment by Sampath-Lokuge** [comment]
@doggy8088 Am I doing it wrong here? i.e. I cannot see it?

![](https://i.imgur.com/BOgfiTB.gif)

**Comment by doggy8088** [comment]
@Sampath-Lokuge You have to type `(` first, then choose the event type. Like this:

![2019-12-05_01-12-51](https://user-images.githubusercontent.com/88981/70164610-717fec00-16fc-11ea-9be2-5adef34bd3a6.gif)

By the way, I think there is a bug in version `0.900.0` (latest version). I just reported it: https://github.com/angular/vscode-ng-language-service/issues/474

**Comment by Sampath-Lokuge** [comment]
@doggy8088 Yes, your right. It is not working on the latest version where I use `v0.900.0`. Thanks for the bug report. I hope they'll fix soon.

**Comment by Sampath-Lokuge** [comment]
I think we need a solution from you here @doggy8088 I don't think `vscode-ng-language-service` solution is enough here?  https://github.com/angular/vscode-ng-language-service/issues/474#issuecomment-562433267

Your thoughts?

**Comment by doggy8088** [comment]
@Sampath-Lokuge They are actually fixing this problem now. Don't worry about it. I think they will fix this soon.

**Comment by Sampath-Lokuge** [comment]
@doggy8088 Aren't they asking something from you here? https://github.com/angular/vscode-ng-language-service/issues/474#issuecomment-562433267 I didn't get what they tried to show there.

**Comment by johnpapa** [comment]
this is part of the angular language service
