### ISSUE TITLE
RxJs operators reference needs to be updated

### ISSUE THREAD

**Issue by HammNCheez** [johnpapa/vscode-angular-snippets#106]
### OS and Version?
Windows 10

### Versions
 8.3.0

### Repro steps
 use snippet a-http-interceptor-logging

### The log given by the failure.
'.../rxjs' has no exported member tap. 

### Mention any other details that might be useful.
RxJs operators got moved to the /operators directory. The snippet adds the import:
 - import { Observable, tap } from 'rxjs';

When it should be adding two imports:
 - import { Observable } from 'rxjs';
 - import { tap } from 'rxjs/operators';

This could be happening in other snippets, but I haven't used them extensively yet.

**Comment by johnpapa** [comment]
fixed in v9
