### ISSUE TITLE
The extension cannot be installed into VSO

### ISSUE THREAD

**Issue by egamma** [johnpapa/vscode-angular-snippets#109]
![image](https://user-images.githubusercontent.com/172399/74417650-57266500-4e47-11ea-94e6-0c216be63c8d.png)

The reason is that the extension is defined to be a strict UI extension (`"extensionKind"; ["ui"]`). This means it only runs in the UI extension host which is not available in VSO.

To enable that the extension and its snippets work in VSO the extensionKind should be changed to ("extensionKind"; ["ui", "workspace"]`. 

See also #111

**Comment by johnpapa** [comment]
fixed in 9.1.2
