### ISSUE TITLE
Faulty implementation of the 'a-route-params-subscribe' snippet

### ISSUE THREAD

**Issue by Schmaga** [johnpapa/vscode-angular-snippets#113]
**Used OS:** Windows 10
**Version:** Angular 9 (any version) and Snippets of latest Version since change in #95

Hi everyone.

I just noticed that the implementation of the 'a-route-params-subscribe' snippet seems to have been changed to a faulty one during the issue #95

There it was changed to this implementation to use _paramMap_ instead of _params_:
```ts
this.route.paramMap
  .pipe(switchMap(params => params.get('id')), tap(id => (this.id = +id)))
  .subscribe(id => { });
```

But the _switchMap_ operator in this example is used wrongly. Using _switchMap_ this way with an example input of '123' for the id will result in the subscription being triggered three times, each with values 1, then 2 and 3. If anyone will then start another observable call based on these results, he or she will trigger those calls many many times with wrong parameters. Because the _switchMap_ operator will flatten the string (or array if its one). I think it should at least be changed to the following code, because this was probably the original intention:
```ts
this.route.paramMap
  .pipe(map(params => params.get('id')), tap(id => (this.id = +id)))
  .subscribe(id => { });
```

Or am I getting the intention of the snippet wrong?

**Comment by stefnotch** [comment]
Author of the PR here: Indeed, that is a mistake, I should have caught that.

Would you mind submitting a PR with a fix?

**Comment by Schmaga** [comment]
Will do. Trying to get around to that later. My first OSS PR Ever :)

**Comment by Schmaga** [comment]
Here we go, opened the PR. Didn't know what to make of most of the PR template parts for such a small PR. Just let me know if you need more info.
