### ISSUE TITLE
Not appearing in Nuget package manager search in visual studio 2019

### ISSUE THREAD

**Issue by Basoya111** [johnpapa/vscode-angular-snippets#115]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution).macOS(Yosemite ? El Capitan? Sierra ?)
windows 10
### Versions
  >

### Repro steps
  >

### The log given by the failure.
>

### Mention any other details that might be useful.
The package is not appearing in search, also another package 'Debugger for Chrome' is not appearing in Manage extensions or Nuget package manager, and I am unable to install the Angular snippets' extension from the web as when I click on the install button nothing happens.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
This is not in nuget
