### ISSUE TITLE
Adapting snippets to WebStorm

### ISSUE THREAD

**Issue by prigara** [johnpapa/vscode-angular-snippets#12]
We'd really love to adapt and bundle these Angular 2 snippets with the [AngularJS plugin](https://github.com/JetBrains/intellij-plugins/tree/master/AngularJS) for WebStorm and other IntelliJ IDEA-based IDEs. Would you mind us doing that? Thank you!

**Comment by johnpapa** [comment]
Certainly. Thanks for asking. Any mention where they came from is appreciated , but not required :)

Please feel free to add a PR to the official angular.io docs too, for a link from the official A2 style guide. I added vs code snippets link there.

**Comment by prigara** [comment]
Thank you, John!
