### ISSUE TITLE
Add SystemJS Module Loader Snippet

### ISSUE THREAD

**Issue by marcelcremer** [johnpapa/vscode-angular-snippets#13]
SystemJS uses __moduleName instead of module.id.

I will add a PR.

**Comment by johnpapa** [comment]
If you choose commonjs as the module type in the tsconfig.json file then module.id works.

PS - The A2 team is working on other means for this too .. so for now I'll keep this as is.

**Comment by marcelcremer** [comment]
Hello John,

okay thank you. I've created a template for me now and wait for the changes that are coming :)

Best Regards
Marcel
