### ISSUE TITLE
Enable Angular Snippets to run on VS Code on the web

### ISSUE THREAD

**Issue by digitarald** [johnpapa/vscode-angular-snippets#133]
👋 I'm Harald, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser. You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web).

We'd like to ensure that Angular Snippets can run in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

* In VS Code for the Web, both the UI and extension host run inside the browser.
* A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
* Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
* There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

Feel free to reach out to me if you have questions or if I can help somehow. Thank you

**Comment by johnpapa** [comment]
How do you enable an extension for the web, when the extension is just snippets? There is no "web" folder in my out / dist folder.

The docs say I need this setting, but I see other snippet extensions are available in vscode.dev but they do not have the "browser" set in their package.json files


Any help is appreciated

**Comment by bamurtaugh** [comment]
Thanks for looking into this, @johnpapa! 

@aeschli @tanhakabir do you have insights into John's question above?

**Comment by tanhakabir** [comment]
I believe other snippet extensions don't contain code but you have the command "angular.configureExpressServer" which contains code and some of it is not web friendly like your usage of `fs` in packageJson.ts

**Comment by johnpapa** [comment]
ah. I had forgotten that I have code to create a file in here. I can remove that, thanks.

My original question remains:

> How do you enable an extension for the web, when the extension is just snippets? There is no "web" folder in my out / dist folder. The docs say I need this setting, but I see other snippet extensions are available in vscode.dev but they do not have the "browser" set in their package.json files

**Comment by aeschli** [comment]
If the extension has only snippets (using the contribution point [contributes.snippets](https://code.visualstudio.com/api/references/contribution-points#contributes.snippets)) (or other declarative contributions) it works as both a web and node extension, no changes needed.
If the extension has code (a `main` entry point in `package.json`) it also needs a `browser` entry point to work in a web extension host. It can also point to an empty stub.

**Comment by johnpapa** [comment]
done
