### ISSUE TITLE
ng template snippets is outdated

### ISSUE THREAD

**Issue by mehdad-hussain** [johnpapa/vscode-angular-snippets#138]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> Windows 11 pro

### Mention any other details that might be useful.
`<ng-template [ngTemplateOutlet]="outlet" [ngOutletContext]="context"></ng-template>`

ng template snippets is outdated. because ngOutletContext is depricated. I think it should be updated.

> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
- removed ngTemplate due to syntax changes
