### ISSUE TITLE
Automate build/publish

### ISSUE THREAD

**Issue by PieterjanDeClippel** [johnpapa/vscode-angular-snippets#141]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
 > N/A

### Versions
  > N/A

### Description
I've improved the [following Github action](https://github.com/HaaLeo/publish-vscode-extension) to not throw an error when a VS Code extension is already present in the Marketplace.
- [Github Action](https://github.com/MintPlayer/publish-vscode-extension)
- [Usage](https://github.com/MintPlayer/mintplayer-ng-bootstrap/blob/master/.github/workflows/publish-master.yml#L274-L280)

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
wanna make a PR?
