### ISSUE TITLE
CanActivate is deprecated. Provide a snippet for CanActivateFn

### ISSUE THREAD

**Issue by iabu94** [johnpapa/vscode-angular-snippets#142]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> Windows 11

### Versions
  > 16.0.1

### Repro steps
  > 

### The log given by the failure.
>

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johnpapa** [comment]
fixed in v18
