### ISSUE TITLE
Add control flow snippets

### ISSUE THREAD

**Issue by jpike88** [johnpapa/vscode-angular-snippets#144]
https://blog.angular.io/meet-angulars-new-control-flow-a02c6eee7843

**Comment by jpike88** [comment]
@GeorgeKnap @johnpapa any plans for this?

**Comment by doggy8088** [comment]
@jpike88 The control flow snippets seems already built-in into [Angular Language Service](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template).

**Comment by johnpapa** [comment]
Yes, they seem to be built into the language service. If you feel we should add them still, please create a PR for consideration.  I appreciate the help - thanks!
