### ISSUE TITLE
Name: Angular 2 TypeScript Test Snippets Id: MarinhoBrandao.Angular2Tests Description: Angular 2 TypeScript test snippets (updated up to Angular 2.1.2) Version: 0.7.3 Publisher: Marinho Brandao VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=MarinhoBrandao.Angular2Tests

### ISSUE THREAD

**Issue by whitemossyoak64** [johnpapa/vscode-angular-snippets#145]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution).macOS(Yosemite ? El Capitan? Sierra ?)

### Versions
  >

### Repro steps
  >

### The log given by the failure.
>

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by Whitemossyoak64** [comment]
Idk
