### ISSUE TITLE
Angular 2 Live Templates for WebStorm

### ISSUE THREAD

**Issue by MrZaYaC** [johnpapa/vscode-angular-snippets#15]
Hi, I have made the script to convert your VS Code snippets to WebStorm LiveTemplates. 
Could you add link to my repo in this project read me file?
(https://github.com/MrZaYaC/ng2-webstorm-snippets)

**Comment by johnpapa** [comment]
The WebStorm team had already made a set of these, they had told me. Can you check with them?

**Comment by MrZaYaC** [comment]
@johnpapa I was create this issue before WebStorm team made its own. The main point of my repo is to convert your snippets into JetBrains Live templates, it is now only for WebStorm but for all JetBrains IDE`s. Also WebStore team had created their own templates. Any way, it is just proposal about mention my plugin in your repo. You able to close this issue any time. Thank you for replay.

**Comment by johnpapa** [comment]
thanks
