### ISSUE TITLE
Dangling comma's

### ISSUE THREAD

**Issue by SamVerschueren** [johnpapa/vscode-angular-snippets#21]
I'm not sure if this was done on purpose, but quite a lot of the snippets have dangling comma's like the `NgModule`.

``` ts
import { NgModule } from '@angular/core';

import { NameComponent }   from './name.component';

@NgModule({
    imports: [],
    exports: [],
    declarations: [NameComponent],
    providers: [],                    // < Here
})
export class NameModule { }
```

Other snippets have that as well. I know some people like dangling comma's due to the fact that diffs tend to be smaller if you add extra properties at the end. Just wanted to ask first before doing a PR and remove them.

**Comment by michaeljota** [comment]
I think this is intencional. This would be a wanted behavior.

**Comment by johnpapa** [comment]
I do this in TypeScript because it happily ignores them and it makes it super helpful when moving lines or copying and pasting or commenting them out.

**Comment by SamVerschueren** [comment]
Alright, thanks for answering this!
