### ISSUE TITLE
Can't hint deep

### ISSUE THREAD

**Issue by keyiis** [johnpapa/vscode-angular-snippets#25]
vscode:1.5.3
vscode-angular2-snippets version 1.0.1
![qq 20160930103803](https://cloud.githubusercontent.com/assets/7766085/18979044/4be3d2f8-86fa-11e6-9ffe-c969fcf44428.jpg)

**Comment by SamVerschueren** [comment]
This is not an issue with this plugin, it's an issue because VS Code does the (S)CSS linting and `/deep/` is not part of that.

**Comment by johnpapa** [comment]
right. sorry
