### ISSUE TITLE
Suggestion: routerLinkActive and routerLinkActiveOptions

### ISSUE THREAD

**Issue by doggy8088** [johnpapa/vscode-angular-snippets#26]
These two directive may add to your vscode-angular2-snippets.  Thanks!

**Comment by johnpapa** [comment]
hmmm ... got any suggestions for how it would look?

**Comment by doggy8088** [comment]
It's something like this.  When typing `ng2-routerLinkActive`, press `tab`.  The code snippets shown:

> routerLinkActive="`active`" [routerLinkActiveOptions]="`{exact: true}`"

**Comment by johnpapa** [comment]
I do it like this ...

```
  <div class="mdl-navigation">
    <a *ngFor="let item of menuItems" [routerLink]="item.link" class="nav-link"
    routerLinkActive="router-link-active"
    href="">{{item.caption}}</a>
  </div>
```

**Comment by johnpapa** [comment]
added in 2.12
