### ISSUE TITLE
Snippets with module:module.Id

### ISSUE THREAD

**Issue by theDiverDK** [johnpapa/vscode-angular-snippets#27]
Hi John

Thanks for a nice snippet pack.

Could you somehow make it configurable wether to add 'module : module.Id' or not?

When using Angular Cli for compiling and all that, due to (i think) webpack, that line is giving compile errors.

**Comment by SamVerschueren** [comment]
VS Code doesn't allow configuration for snippets. I'm using `angular-cli` as well and I must say that it doesn't fail with `module.id`. It's also available in Webpack so it should work.

**Comment by johnpapa** [comment]
The CLI shouldnt care about this ... I'm checking

**Comment by johnpapa** [comment]
verified that the CLI is happy with or without now

**Comment by SamVerschueren** [comment]
I noticed that if you compile for production `ng build --aot --prod`, the CLI fails when you have `moduleId: module.id`.

**Comment by johnpapa** [comment]
This should be resolved as of this PR which is in the next release RC.1

https://github.com/angular/angular-cli/pull/5193
