### ISSUE TITLE
Error while installing extension

### ISSUE THREAD

**Issue by HegdeSach** [johnpapa/vscode-angular-snippets#45]
I am getting the following error in my Visual Studio Code IDE 

![image](https://cloud.githubusercontent.com/assets/21358983/23501773/44768d42-ff5b-11e6-989a-60e8f458c636.png)

If it is issue with proxy then how to set proxy for Visual Studio Code?

**Comment by johnpapa** [comment]
please search  the vscode github repo's issues for this, or report there.

thanks
