### ISSUE TITLE
Missing export statement on Directive

### ISSUE THREAD

**Issue by aboudard** [johnpapa/vscode-angular-snippets#5]
If I'm not wrong, the export is missing for the ng2directiveSimple snippet.
Totally awesome plugin though :+1:

**Comment by johnpapa** [comment]
hmm. i dont see a directive in this repo. what do you mean?

**Comment by aboudard** [comment]
Ok, I'm confused, as I'm testing two VSCode extensions, I mixed up !
This is the one : https://marketplace.visualstudio.com/items/UVBrain.Angular2
Now the issue is resolved :D
