### ISSUE TITLE
Not obvious how to use a-http-get

### ISSUE THREAD

**Issue by wesleycho** [johnpapa/vscode-angular-snippets#51]
At first glance, it does not seem obvious how to use several of the snippets - for example, just entering in `a-http-get` and tabbing does not apply the snippet in VS Code. Similarly with `a-service-http`.

I could file a PR updating the README if anyone has any ideas on how to use them.

**Comment by johnpapa** [comment]
i'm not sure what you are experiencing. Cna you elaborate?

**Comment by alejandrohn** [comment]
This snippets the content-type is text/plain by default, it could add 

 let headers = new Headers();
 headers.append('Content-Type', 'application/json; charset=utf-8');

 return this.http.get(url, headers).map((response: Response) => response.json());

**Comment by johnpapa** [comment]
is there an action here?
