### ISSUE TITLE
File templates

### ISSUE THREAD

**Issue by simonech** [johnpapa/vscode-angular-snippets#52]
More of a question then an issue: not sure about VSCode extensibility, but would it be possible to have file templates? which also create all the related files, like it happens with the ng cli, but when you cannot use the cli? For example when using the JavaScriptServices for ASP.NET Core I don't want to bring in all the stuff added by the CLI.

**Comment by jboone0052** [comment]
I know this doesn't help with this, but fyi, you can create a new cli project, then copy the .angular-cli.json file into the root of the project, you can then use cli code generation on an existing project.

**Comment by simonech** [comment]
So only requirement for having generation of files via the angularcli is to have the config file. 
Cool 😎

**Comment by jboone0052** [comment]
I just tested it and you have to do npm install --save-dev @angular/cli and have the .angular-cli.json file in the root of you project to work.

**Comment by johnpapa** [comment]
file templates would be easiest from the CLI
