### ISSUE TITLE
shortcut doesn't show up first time I type on newly generated typsescript files

### ISSUE THREAD

**Issue by jboone0052** [johnpapa/vscode-angular-snippets#53]
In a typescript file when I got to insert a snippet such as a-component, when I type "a-" the first time i'm in a file the angular snippets don't show in the code completion. If i backspace and remove the "a-" and then type in "a-" again the available snippets show up. This only happens in newly created typescript files. Existing typescript files don't have this issue.

**Comment by johnpapa** [comment]
not sure. sounds like a vs code thing. try searching their issues in github

**Comment by victormejia** [comment]
@jboone0052 I was having a similar issue, so just added this setting and seems to have fixed it:

```
"editor.tabCompletion": true
```
