### ISSUE TITLE
Snippets are not in sync with Angular CLI snippets

### ISSUE THREAD

**Issue by ajit-kumar-azad** [johnpapa/vscode-angular-snippets#55]
I noticed that the snippet that this extension generates and what Angular CLI generates are not same. It should be a good idea to keep them in sync so that irrespective of what tools people use, the snippets are consistent.

**Comment by johnpapa** [comment]
Can you elaborate on how they aren't in synch? If you create specific issues, I can work on them.

**Comment by johnpapa** [comment]
closing due to no reply.

if there is something specific you'd like to see, let me know
