### ISSUE TITLE
Is it possible to make HTML snippets to work in template strings?

### ISSUE THREAD

**Issue by dKab** [johnpapa/vscode-angular-snippets#67]
HTML snippets such as ngFor and ngIf are not working in .ts files, when we are defining templates in "`" (back-ticks) Is it possible to make them work there?

**Comment by johnpapa** [comment]
try my angular essentials extension. it comes with an extension that enables this for inline templates

**Comment by abierbaum** [comment]
@johnpapa Which extension is it that enables the snippets for use in templates?  I installed the angular essentials plugin and it still is not working for me.  (best guess was that angular2-inline was supposed to make the inline templates use the HTML language mod or something?)
