### ISSUE TITLE
What is the font and theme used in screenshot?

### ISSUE THREAD

**Issue by manojp1988** [johnpapa/vscode-angular-snippets#80]
I don't know where to ask about this. The font and theme showed in the screenshot is awesome. can you tell me what they are ?

**Comment by mantyz** [comment]
@manojp1988, It seems like that is a "[Winter is Coming Theme](https://marketplace.visualstudio.com/items?itemName=johnpapa.winteriscoming)".

**Comment by manojp1988** [comment]
thank you
