### ISSUE TITLE
import snippet needs a replace from " quotes to '

### ISSUE THREAD

**Issue by bhushanvaidya3** [johnpapa/vscode-angular-snippets#81]
Whenever i use the import snippet, it generates the import statement with " quotes. The tslint throws a error suggestion a replace with ' quotes.

System:
VS Code 1.10+
Angular 5+
Ng Cli 1.7+

Thanks,
Bhushan

**Comment by johnpapa** [comment]
that may be your editorconfig settings.

**Comment by bhushanvaidya3** [comment]
thanks for the update,I will look into it 👍
