### ISSUE TITLE
Suggestion: Use tslint file to apply the correct syntax

### ISSUE THREAD

**Issue by Robouste** [johnpapa/vscode-angular-snippets#87]
It would be very nice if this plugin could use the tslint file to apply the correct syntax. 

In my case, every time I generate some typescripts snippet, I have to replace simple quote with double quote.

**Comment by doggy8088** [comment]
@Robouste You can try [Prettier - Code formatter - Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode), this extension can auto format your code including single-quote or double-quote usage.  You can configure user settings by your own.

**Comment by Robouste** [comment]
It's better with this plugin indeed :) 
I just had to add this in the user config:

```json
"[typescript]": {
	"editor.formatOnSave": true
}
```
