### ISSUE TITLE
[HELP] - proposed ngrx snippets wanted

### ISSUE THREAD

**Issue by johnpapa** [johnpapa/vscode-angular-snippets#93]
Help wanted!

I'm looking to add a series of ngrx snippets to this extension. Please propose them here in the issues and once agreed, y'all can add PRs to add them. Or I can add them if you prefer.

**Comment by wesleygrimes** [comment]
Just brainstorming here before I create actual PR.

I suggest we create snippets for the following:

- `createAction`
- `createAction` w/ `props`
- `createReducer`
- `createEffect`
- `createEffect` w/ API call scaffolded
- `createSelector`

Any others I am missing?

Once we agree on the "what" I will create a PR with a first pass on implementing these.

**Comment by wesleygrimes** [comment]
Also, is `ngrx-*` good for prefixes? 

createAction -> `ngrx-ca`
createAction w/ props - `ngrx-cap`

etc...

**Comment by johnpapa** [comment]
ngrx-create-action

Spelled out please. 

Tabs make it easy.

**Comment by wesleygrimes** [comment]
> ngrx-create-action
> 
> Spelled out please.
> 
> Tabs make it easy.

OK Sounds good.

Something like this?

- createAction - `ngrx-create-action`
- createAction w/ props - `ngrx-create-action-props`
- createReducer - `ngrx-create-reducer`
- createEffect - `ngrx-create-effect`
- createEffect w/ API call scaffolded - `ngrx-create-effect-api`
- createSelector - `ngrx-create-selector`

**Comment by johnpapa** [comment]
closed by #94
