### ISSUE TITLE
a-route-params-subscribe outdated

### ISSUE THREAD

**Issue by stefnotch** [johnpapa/vscode-angular-snippets#95]
> Please provide us with the following information:
> ---------------------------------------------------------------

### OS and Version?
> Windows 10

### Versions
  > 8.1.0 (2019-06-07)

### Repro steps
`a-route-params-subscribe`
creates
```typescript
this.route.params
  .pipe(map(params => params.get('id')), tap(id => (this.id = +id)))
  .subscribe(id => function()());
```

However, [the angular documentation](https://angular.io/guide/router) says
> params—An Observable that contains the required and optional parameters specific to the route. Use paramMap instead.

Also, there doesn't seem to be a reason to write `function()()` in the subscribe part.

So, it should be changed to
```typescript
this.route.paramMap
  .pipe(switchMap(params => params.get('id')), tap(id => (this.id = +id)))
  .subscribe(id => { });
```

**Comment by johnpapa** [comment]
good idea. anyone want to make a PR?

**Comment by Sampath-Lokuge** [comment]
Yes, This is a great thing. Hope @johnpapa will give this to us soon.
