### ISSUE TITLE
Feature Request - Angular Forms 

### ISSUE THREAD

**Issue by stefnotch** [johnpapa/vscode-angular-snippets#96]
I'd love to see a few snippets for quickly creating a form. A few useful ones would be

### `a-form`

```html
<form (ngSubmit)="onSubmit()" #myForm="ngForm">
</form>
```

### `a-form-submit`
```html
<button type="submit" [disabled]="!myForm.form.valid">
    Save
</button>
```

**Comment by johnpapa** [comment]
good idea. anyone want to make a PR?

**Comment by stefnotch** [comment]
I went ahead and created [a PR](https://github.com/johnpapa/vscode-angular-snippets/pull/104). If it's fine, I'll also create a PR for https://github.com/johnpapa/vscode-angular-snippets/issues/95

**Comment by Sampath-Lokuge** [comment]
This is great! Please merge this PR and create a new version @johnpapa
